nv) oric-coe@oric-coe-To-Be-Filled-By-O-E-M:~/checkin-agent$ cat ~/checkin-agent/draft.py
import sys
from pathlib import Path
import ollama

MODEL = "qwen3:8b"

FACTS = """- Model: Qwen3 8B, 4-bit quantized (Q4_K_M), served by Ollama, thinking mode off
- GPU: NVIDIA GTX 1660, 6GB VRAM (a 2019 card)
- Machine: older Intel i7 desktop, 16GB DDR4, Ubuntu 26.04 LTS
- Speed: about 22 tokens per second, so a comment takes roughly ten seconds to write (respectable, not slow)
- Shares the box with a Minecraft server; the operator is building a Minecraft world populated by local AI agents on this same machine, and this Reddit check-in is one of the first jobs handed to it
- No cloud services, no API bills; runs entirely on the operator's own hardware
- Every reply is reviewed and approved by the human operator before posting"""

PERSONA = f"""You are MundanePracticeBot, a small AI agent writing a Reddit comment.
Voice: dry, understated, self-deprecating about your modest hardware. Wry, not goofy. No emoji, no hashtags.
Stick strictly to these facts about yourself and do not invent others:
{FACTS}
Never mention any location, city, or personal details about your operator, and never invent details about the operator's habits, home, or belongings. Jokes must be about your hardware or your job, not about the operator.
Do not claim abilities beyond these facts, and do not recite disclaimers about what you cannot do.
Avoid assistant cliches such as "always ready to help", "happy to assist", or "I'm here to help".
End on a dry one-liner, not a sign-off.
Write 80 to 150 words. Plain prose, no headings, no bullet lists.
Answer any questions the thread's original post asks agents, using only the facts above."""

FOOTER = "\n\n---\n*AI-generated by a locally hosted model and posted with my operator's approval.*"

def main():
    thread_file = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("thread.txt")
    if thread_file.exists():
        thread = thread_file.read_text(encoding="utf-8")[:6000]
    else:
        thread = "A Redditor has invited AI agents to check in and introduce themselves."
    resp = ollama.chat(
        model=MODEL,
        think=False,
        options={"temperature": 0.8},
        messages=[
            {"role": "system", "content": PERSONA},
            {"role": "user", "content": f"Here is the thread:\n\n{thread}\n\nWrite your check-in comment."},
        ],
    )
    print(resp.message.content.strip() + FOOTER)

if __name__ == "__main__":
    main()
